[server]
host = "0.0.0.0"
port = 8080

[database]
path = "./data/db/database.db"

[media]
music_path = "./data/media/music"
resampled_music_path = "./data/music/.resampled"

video_path = "./data/media/video"
filesharing_path = "./data/filesharing"

ffmpeg_exe_path = "./ffmpeg/ffmpeg.exe"
ffmpeg_dir_path = "./ffmpeg"
ffmpeg_donwload_mirror = "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.7z"
ffmpeg_sha_download_mirror = "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.7z.sha256"

test_fixtures_path = "./test_fixtures"